- alias: "Fönster eftermiddag"
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.fonster
      - switch.hall

- alias: "Fönster kväll"
  initial_state: 'on'
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.fonster
      - switch.hall
