- alias: "Fönster på eftermiddag"
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    - service: script.turn_on
      entity_id: script.turn_on_lights_afternoon
    - service: homeassistant.turn_on
      entity_id: switch.hall

- alias: "Fönster av kväll"
  initial_state: 'on'
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    condition: time
    weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
  action:
    service: script.turn_on
    entity_id: script.turn_off_lights_evening

- alias: "Fönster av sen kväll"
  initial_state: 'on'
  trigger:
    platform: time
    at: '00:30:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    service: script.turn_on
    entity_id: script.turn_off_lights_evening

- alias: "Spritskåp på"
  initial_state: 'on'
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.spritskap

- alias: "Spritskåp av"
  initial_state: 'on'
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.spritskap

- alias: "Julgran på"
  initial_state: 'on'
  trigger:
    platform: time
    at: '16:01:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.julgran

- alias: "Julgran av"
  initial_state: 'on'
  trigger:
    platform: time
    at: '23:01:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.julgran
