- alias: "Kök på morgon"
  initial_state: 'on'
  trigger:
    platform: time
    at: "05:10:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: switch.turn_on
    entity_id: switch.switch

- alias: "Kök av förmiddag"
  initial_state: 'on'
  trigger:
    platform: time
    at: "07:45:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: switch.turn_off
    entity_id: switch.switch

- alias: "Fönster på morgon"
  initial_state: 'off'
  trigger:
    platform: time
    at: "05:48:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.turn_on
    entity_id: script.turn_on_lights_morning

- alias: "Fönster av förmiddag"
  initial_state: 'off'
  trigger:
    platform: time
    at: '08:15:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.turn_on
    entity_id: script.turn_off_lights_morning

- alias: "Fönster på nere morgon"
  initial_state: 'off'
  trigger:
    platform: time
    at: "05:20:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.turn_on
    entity_id: script.turn_on_lights_downstairs_morning

- alias: "Fönster av nere förmiddag"
  initial_state: 'on'
  trigger:
    platform: time
    at: "07:45:00"
  action:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.turn_on
    entity_id: script.turn_off_lights_downstairs_morning

- alias: "Vardagsrum på morgon"
  initial_state: 'on'
  trigger:
    platform: time
    at: '05:10:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.hue_color_2

- alias: "Vardagsrum av morgon"
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:15:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue_color_2
