- alias: "Hue på kväll"
  initial_state: 'off'
  trigger:
    platform: time
    at: "18:00:00"
  action:
    - service: light.turn_on
      entity_id:
#        - light.hue_color_1
        - light.hue_color_2
      data:
        rgb_color: [174, 140, 79]
        brightness: 77

- alias: "Hue dämpad på kväll"
  initial_state: 'off'
  trigger:
    platform: time
    at: "21:00:00"
  action:
    - service: light.turn_on
      entity_id:
#        - light.hue_color_1
        - light.hue_color_2
      data:
        rgb_color: [174, 140, 79]
        brightness: 20

- alias: "Hue av natt"
  initial_state: 'off'
  trigger:
    platform: time
    at: "23:00:00"
  action:
    - service: light.turn_off
      entity_id:
 #       - light.hue_color_1
        - light.hue_color_2
